AWSTemplateFormatVersion: "2010-09-09"
Description: "Automated EC2 with restricted SSH access"

Parameters:
  MyIPAddress:
    Type: String
    Description: Enter your public IP in CIDR format (e.g., 192.0.0.0/32)

Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH only from my IP and HTTP from anywhere
      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIPAddress

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro

      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"

      KeyName: my-keypair

      SecurityGroupIds:
        - !Ref MySecurityGroup

      Tags:
        - Key: Name
          Value: jenkins-practice

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt MyEc2Instance.PublicIp
